### ISSUE TITLE
Maybe take out the connection to Microsoft

### ISSUE THREAD

**Issue by phongvdoan** [GotYourBac/gotYourBac#67]
Remember we must not draw attention by slandering the company. Please look for a better way to describe Balmer's Peak

**Comment by phongvdoan** [comment]
Even have a case study or even like in college 'solid' research because we are putting on name on this project we don't to lose trust from customers and any potential employers.

**Comment by martinpapacodes** [comment]
I couldn't find any research(peer-reviewed) that is related to the Ballmer's Peak. I agree on just dropping that page. We have plenty enough of features that are appealing to the audience. It was a fun idea though!
